# Ch4. Numpy基础

In [1]:
import numpy as np
# import matplotlib.pyplot as plt
import pandas as pd

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2=my_arr*2

CPU times: total: 0 ns
Wall time: 9.81 ms


In [3]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

CPU times: total: 266 ms
Wall time: 364 ms


## 4.1 Numpy ndarry:多维数组对象

Numpy的核心特征之一是N-维数组对象 ---ndarray

In [4]:
# aaeouaoeu

In [5]:
# 生成随机数组

data = np.random.randn(2, 3)
data

array([[-0.36132916,  0.79015068, -0.82782219],
       [ 1.18265924, -1.24751053, -1.2788358 ]])

In [6]:
# 给data加上数学操作
print(data * 10)
print(data + data)

[[ -3.61329162   7.90150676  -8.27822191]
 [ 11.82659237 -12.4751053  -12.78835804]]
[[-0.72265832  1.58030135 -1.65564438]
 [ 2.36531847 -2.49502106 -2.55767161]]


In [7]:
# 每一个ndarray对象都有一个shape的属性，用来表示数组中每一维的数量
# 每一个ndarray对象都有一个dtype的属性，用来表示数组的数据类型
print(data.shape)
print(data.dtype)

(2, 3)
float64


### 4.1.1 生成ndarray

In [8]:
# 生成数组最简单的方式使用array函数。array函数接收任意的序列型对象
data1 = [6, 2, 3, 883.2, 0]
arr1 = np.array(data1)

# 同等长度的列表，会自动转换成多维数组
data2 = [[1, 2, 3], [3, 3, 4]]
arr2 = np.array(data2)

data3 = [[[1, 2], [2, 3]], [[3, 4], [4, 5]]]
arr3 = np.array(data3)
arr3.shape

(2, 2, 2)

In [9]:
# 可以通过检查ndarray的ndim属性来确认数组的维度
arr2.ndim
arr3.ndim

3

In [10]:
# zeros可以一次性创建全0数组
print(np.zeros(5))

# ones可以一次性创建全1数组
print(np.ones(4))

# 如果需要创建高维的数组，需要传递一个shape的元组
print(np.ones((2, 3, 2)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


empty用来创建没有初始化数值的数组。如果用np.empty来生成全0的数组，并不安全，因为它可能会返回未初始化的垃圾数值

In [11]:
# arange 是python的range的数组版

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

### 4.1.2 ndarray的数据类型

In [12]:
# astype可以显示得转换数据类型
arr = np.array([1, 2, 3])
print(arr)
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

[1 2 3]
int32
float64


使用astype时总是生成一个新的数组，即使传入的dtype与之前的一样

### 4.1.3 Numpy数组算术

In [13]:
# 数组可以进行向量化的操作
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr * arr

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [15]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [16]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
arr2 = np.arange(2, 8).reshape(2, 3)
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
# 同尺寸数组之间的比较，会产生一个同尺寸的布尔值数组
arr2 > arr

array([[ True,  True,  True],
       [ True,  True,  True]])

### 4.1.4 基础索引与切片

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# 数组的切片是原数组的视图，任何对切片的修改都会反映到原数组上
arr[5] = 55
arr

array([ 0,  1,  2,  3,  4, 55,  6,  7,  8,  9])

In [21]:
arr[2:4] = 22
arr

array([ 0,  1, 22, 22,  4, 55,  6,  7,  8,  9])

In [22]:
# 二维数组中，每个索引值对应的是一个一维数组
arr2d = np.arange(1, 10).reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


In [24]:
arr3d = np.arange(1, 13).reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### 4.1.4.1 数组的切片索引

In [26]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[:2, 2:]

array([[3],
       [6]])

In [29]:
arr2d[:2, 2]

array([3, 6])

In [30]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [31]:
arr2d[:, 0]

array([1, 4, 7])

In [32]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [33]:
arr2d[2].shape

(3,)

In [34]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
t = np.arange(1, 10).reshape(3, 3)
d = t[2]
d1 = t[2, :]
d2 = t[2:, :]
print(d)
print(d.shape)

print(d1)
print(d1.shape)

print(d2)
print(d2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
(3,)
[7 8 9]
(3,)
[[7 8 9]]
(1, 3)


### 4.1.5 布尔索引

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)
data

array([[-0.23353741,  0.56389778, -0.0156439 , -0.72687106],
       [-0.45973304, -1.30398605, -0.40805423,  1.09278552],
       [ 1.29038043,  1.00668   ,  1.06287504, -0.13548722],
       [-0.97656885, -0.34994333, -1.43882584,  1.02323803],
       [-0.52402739, -0.88641185, -0.59459995,  2.21529211],
       [ 0.86167122, -0.07503474,  1.06012978,  0.03007689],
       [ 1.49426385,  0.72687347,  0.24525889, -2.13711674]])

In [36]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [37]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [38]:
# 选中'Bob'所在的行
data[names == 'Bob']

array([[-0.23353741,  0.56389778, -0.0156439 , -0.72687106],
       [-0.97656885, -0.34994333, -1.43882584,  1.02323803]])

In [39]:
# 使用~对条件取反
data[~(names == 'Bob')]
# 和python中的不同，多个布尔值联合需要使用'&'和'|'

array([[-0.45973304, -1.30398605, -0.40805423,  1.09278552],
       [ 1.29038043,  1.00668   ,  1.06287504, -0.13548722],
       [-0.52402739, -0.88641185, -0.59459995,  2.21529211],
       [ 0.86167122, -0.07503474,  1.06012978,  0.03007689],
       [ 1.49426385,  0.72687347,  0.24525889, -2.13711674]])

### 4.1.6 神奇索引

In [40]:
# 可以通过传递一个包含指明所需顺序的列表或数组来完成
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)
print(arr[[4, 0, 3, 6]])

# 也可以传递多个索引数组，这样会选出一维数组
arr = np.arange(32).reshape((8, 4))
arr

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [0. 0. 0. 0.]
 [3. 3. 3. 3.]
 [6. 6. 6. 6.]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
arr[[0, 2, 4, 6], [1, 1, 0, 3]]

array([ 1,  9, 16, 27])

### 4.1.7 数组转置和换轴

In [42]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
# 转置。转置可以返回底层数据的视图，而不需要复制任何内容
arr.T
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
# 使用np.dot进行矩阵的内积
arr = np.random.randn(6, 3)
arr

array([[-1.28874163,  1.32164336, -1.06971403],
       [-0.69260333, -0.39802627,  0.05136071],
       [ 0.62873002, -0.13542346,  0.79749422],
       [ 2.0461983 , -0.29065108,  1.60830907],
       [-0.73657719, -0.76367394,  1.85252783],
       [-1.70290855, -0.00417201,  1.39432808]])

In [45]:
np.dot(arr.T, arr)

array([[10.16522677, -1.53784768,  1.39639728],
       [-1.53784768,  2.59119895, -3.43022394],
       [ 1.39639728, -3.43022394,  9.74559128]])

In [46]:
arr = np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
# transpose可以传递一个元组
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [48]:
arr.transpose(2, 0, 1)

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [49]:
arr.transpose(2, 1, 0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [50]:
# ndarray 有swapaxes方法 ，该方法接收一对轴编号作为参数，并对轴进行调整用于重组数据
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
arr.swapaxes(1, 2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

## 4.2 通用函数
可以对ndarray数据中进行逐元素操作的函数

In [52]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [55]:
d = np.array([1, 2, 1 / 3])
np.isfinite(d)

array([ True,  True,  True])

## 4.3 使用数组进行面向数组编程

In [56]:
# 简单示例 meshgrid函数
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [57]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [58]:
#plt.imshow(z, cmap=plt.cm.gray)
#plt.colorbar()
#plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

### 4.3.1 将条件逻辑作为数组操作

In [59]:
# numpy.where 操作
xarr = np.random.randn(5)
yarr = np.random.randn(5)
print(xarr)
print(yarr)
# 取两个数组中更大的值
result = np.where(xarr > yarr, xarr, yarr)
print(result)

[ 0.19761068 -2.46284339 -0.49061574  0.92620949  0.29847603]
[1.2747082  0.56838282 2.21526111 0.87747269 0.23568424]
[1.2747082  0.56838282 2.21526111 0.92620949 0.29847603]


传递给`np.where`的数组既可以是同等大小的数组，也可是标量

### 4.3.2 数学和统计方法 

In [60]:
# 可以以某一个轴对多维数组进行统计(求和、求平均等)
data = np.arange(24).reshape(2, 3, 4)
print(data)
print('--------------')
print(data.sum(axis=0))
print('--------------')
print(data.sum(axis=1))
print('--------------')
print(data.sum(axis=2))
# 其中axis参数可以去掉
print('--------------')
print(data.sum(2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--------------
[[12 15 18 21]
 [48 51 54 57]]
--------------
[[ 6 22 38]
 [54 70 86]]
--------------
[[ 6 22 38]
 [54 70 86]]


In [61]:
# cumsum和cumprod分别是从0开始元素累积和，从0开始元素累积积
arr = np.array([9, 1, 2, 3, 4])
print(arr.cumsum())
print(arr.cumprod())

[ 9 10 12 15 19]
[  9   9  18  54 216]


In [62]:
# cumsum 可以在指定轴向根据较低维度的切片进行部分聚合
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [64]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [65]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 4.3.3 布尔值数组方法 

In [66]:
# sum可以计算布尔值数组中True的个数
arr = np.random.randn(100)
(arr > 0).sum()

56

In [67]:
# any 检查数组中是否至少有一个True
# all 检查是否每个值为True
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


### 4.3.4 排序

In [68]:
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)

[ 0.44519895  2.12454098 -0.26296284 -0.65994534  0.30385817 -0.27874852]
[-0.65994534 -0.27874852 -0.26296284  0.30385817  0.44519895  2.12454098]


In [69]:
arr = np.random.randn(5, 3)
arr

array([[-0.44194687, -0.11387224,  0.93860704],
       [ 0.81578629, -1.75098415,  0.05250003],
       [ 1.80011173, -0.69424266,  0.00511079],
       [ 1.87822845, -1.25790169,  1.38657859],
       [ 0.26515073, -0.32820595,  0.95190624]])

In [70]:
arr.sort(0)
arr

array([[-0.44194687, -1.75098415,  0.00511079],
       [ 0.26515073, -1.25790169,  0.05250003],
       [ 0.81578629, -0.69424266,  0.93860704],
       [ 1.80011173, -0.32820595,  0.95190624],
       [ 1.87822845, -0.11387224,  1.38657859]])

In [71]:
# np.sort方法返回的是已经排序好的数组拷贝，不是对原数组按位置排序

### 4.3.5 唯一值与其他集合逻辑

In [72]:
# np.unique返回数组中唯一值排序后形成的数组
names = np.array(['aaa', 'bbb', 'aaa', 'b', 'ccc', 'b'])
np.unique(names)

array(['aaa', 'b', 'bbb', 'ccc'], dtype='<U3')

# Ch5 Pandas入门

## 5.1 Pandas数据结构介绍

### 5.1.1 Series
Series是一种一维的数组类型对象，它包含了值序列，并包含了数据标签，也称为索引(Index)

In [73]:
obj = pd.Series([[4, 7, -5, 3]])
obj

0    [4, 7, -5, 3]
dtype: object

In [74]:
obj.values

array([list([4, 7, -5, 3])], dtype=object)

In [75]:
obj.index

RangeIndex(start=0, stop=1, step=1)

In [76]:
# 可以创建带标签的序列序列
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [77]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [78]:
# 可以在数据中使用标签来进行索引
print(obj2['a'])
print(obj2[['c', 'a', 'd']])

-5
c    3
a   -5
d    4
dtype: int64


In [79]:
# 使用布尔值进行过滤
print(obj2 > 0)
print(obj2[obj2 > 0])

d     True
b     True
a    False
c     True
dtype: bool
d    4
b    7
c    3
dtype: int64


In [80]:
# 使用字典生成Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [81]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [82]:
# pandas 使用isnull和notnull函数来检查缺失数据
print(pd.isnull(obj4))
print(pd.notnull(obj4))
# isnull 和notnull也是Series的实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [83]:
# 自动索引对齐是一个有用的特性
print(obj3)
print(obj4)
print(obj3 + obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


### 5.1.2 DataFrame
DataFrame 表示的是矩阵的数据表
有多种方式可以构建DataFrame

In [84]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)
print(frame)
# 对于大型DatFrame, head方法只会选出前五行
print()
print(frame.head())

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9


In [85]:
# 如果传的列不在字典中，将会在结果中出现缺失值
frame2 = pd.DataFrame(data,
                      columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)
print(frame2.columns)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [86]:
# 选取某一列
print(frame2['debt'])
print(frame2.year)
print()
# 选取某一万
print(frame2.loc['three'])

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object
one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [87]:
# 修改列的引用
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [88]:
frame2['debt'] = np.arange(6)

In [89]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [90]:
# 可以使用loc 选行选取
frame2.loc['three']  # 类型是Series
# type(frame2.loc['three'])

year     2002
state    Ohio
pop       3.6
debt        2
Name: three, dtype: object

In [91]:
# del 关键字可以删除DateFrame的列
frame2['eastern'] = frame2.state == 'Ohio'
del frame2['eastern']

从DataFrame中选取的列是数据的视图，而不是拷贝

In [92]:
# 另一种构建DataFrame的方式是传入嵌套字典，字典的Key会作为列，字典内部的键作为行索引
pop = {
    'Nevada': {
        2001: 2.4,
        2002: 2.9
    },
    'Ohio': {
        2000: 1.5,
        2001: 1.7,
        2002: 3.6
    }
}
frame3 = pd.DataFrame(pop)
print(frame3)
print()
print(frame3.T)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5


In [93]:
# DataFrame的构造函数9种输入
# 1--2D ndarray--数据的矩阵，行和列的标签是可选参数
print(pd.DataFrame(np.arange(15).reshape(3, 5)))
print()
print(pd.DataFrame(np.arange(15).reshape(3, 5), index=range(2, 5)))
print()
print(pd.DataFrame(np.arange(15).reshape(3, 5), index=[ch for ch in 'abc']))
print()
print(
    pd.DataFrame(np.arange(15).reshape(3, 5),
                 index=[ch for ch in 'abc'],
                 columns=range(10, 15)))
print()
print(
    pd.DataFrame(np.arange(15).reshape(3, 5),
                 index=[ch for ch in 'abc'],
                 columns=[ch for ch in 'zyxtt']))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

    0   1   2   3   4
2   0   1   2   3   4
3   5   6   7   8   9
4  10  11  12  13  14

    0   1   2   3   4
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

   10  11  12  13  14
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

    z   y   x   t   t
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14


In [94]:
# 2--数组、列表和元组构成的字典
# 2.1 数组构成的字典
dic1 = {'a': [1, 2, 3], 'b': [4, 5, 6]}
print(pd.DataFrame(dic1))
print()
dic2 = {'a': (1, 2, 3), 'b': (4, 5, 6)}
print(pd.DataFrame(dic2))
print()
dic3 = {'a': np.arange(3), 'b': np.arange(4, 7)}
print(pd.DataFrame(dic3))

   a  b
0  1  4
1  2  5
2  3  6

   a  b
0  1  4
1  2  5
2  3  6

   a  b
0  0  4
1  1  5
2  2  6


In [95]:
# 3-- Series构成的字典--每个值成为一列
s1 = pd.Series(range(3), index=['a', 'b', 'c'])
s2 = pd.Series(range(4, 7), index=['b', 'c', 'd'])
dic4 = {'k1': s1, 'k2': s2}
print(pd.DataFrame(dic4))

    k1   k2
a  0.0  NaN
b  1.0  4.0
c  2.0  5.0
d  NaN  6.0


In [96]:
# 4--字典或者Series构成的列表--
lst = []
dic5 = {1: 10, 2: 20}
dic6 = {2: 30, 3: 40}
lst.append(dic5)
lst.append(dic6)
print(print(pd.DataFrame(lst)))

      1   2     3
0  10.0  20   NaN
1   NaN  30  40.0
None


### 5.1.3 索引对象

In [97]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
type(index)
# 索引对象是不可变的，所以是无法修改索引对象的

pandas.core.indexes.base.Index

In [98]:
print(frame3)
print(frame3.columns)
print(type(frame3.columns))  # DataFrame的Columns是索引对象
# Pandas索引对象也可以包含重复标签
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
print(dup_labels)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5
Index(['Nevada', 'Ohio'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
Index(['foo', 'foo', 'bar', 'bar'], dtype='object')


## 5.2 基本功能 

### 5.2.1 重建索引

In [99]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [100]:
# 使用reindex
obj2 = obj.reindex(['a', 'b', 'c', 'd'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [101]:
# 使用ffill方法 在重建索引时，插值， ffill方法会将值前向填充
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 3, 6])
obj3

0      blue
3    purple
6    yellow
dtype: object

In [102]:
obj3.reindex(range(8), method='ffill')

0      blue
1      blue
2      blue
3    purple
4    purple
5    purple
6    yellow
7    yellow
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3),
                     index=[ch for ch in 'acd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [104]:
frame2 = frame.reindex([ch for ch in 'abcd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [105]:
# 使用columns进行列的地重建索引
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [106]:
# 使用loc进行重建索引
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

### 5.2.2 轴向上删除条目

In [ ]:
obj = pd.Series(np.arange(5.), index=[ch for ch in 'abcde'])
obj

In [ ]:
new_obj = obj.drop('c')
new_obj

In [ ]:
obj.drop(['d', 'c'])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['One', 'two', 'three', 'four'])
data

In [ ]:
data.drop(['Colorado', 'Ohio'])
data

In [ ]:
# 按列删除，通过传递axis=1或axis='columns'
# 或者 data.drop('two',1) 或者 data.drop('two',axis='columns')
data.drop('two', axis=1)

In [ ]:
# drop的时候增加 inplace=True，会在原对象上操作
obj.drop('c', inplace=True)

In [ ]:
obj

### 5.2.3 索引、选择与过滤

In [ ]:
obj = pd.Series(np.arange(4.), index=[ch for ch in 'abcd'])
obj

In [ ]:
obj['b']

In [ ]:
obj[1]

In [ ]:
obj[2:4]

In [ ]:
obj[['b', 'a', 'd']]

In [ ]:
obj[[1, 3]]

In [ ]:
# Series的切片包含闭合区间
obj['b':'c']

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data['two']

In [ ]:
# 选择2列
data[['one', 'two']]

In [ ]:
# 过滤行
data[:2]

In [ ]:
data[data['three'] > 5]

In [ ]:
data < 5

In [ ]:
data[data < 5]

#### 5.2.3.1 使用loc和iloc选择数据

In [ ]:
# loc--使用轴标签选择数据
# iloc--使用整数标签选择数据
print(data)
data.loc['Colorado', ['two', 'three']]

In [ ]:
# 使用iloc进行数据数据选择
data.iloc[2, [3, 0, 1]]

In [ ]:
# 索引功能还能用于切片
data.loc[:'Utah', 'two']

data.iloc[:, :3][data.three > 5]

In [ ]:
data.iat[1, 1]

### 5.2.4 整数索引

In [ ]:
# 使用iloc进行整数索引
ser = pd.Series(np.arange(3))
ser

In [ ]:
ser.iloc[1:3]

### 5.2.5 算术和数据对齐
不同索引对象之间的算术行为

In [ ]:
s1 = pd.Series(range(4), index=[ch for ch in 'abcd'])
s2 = pd.Series(range(2, 6), index=[ch for ch in 'bcde'])
print(s1)
print(s2)
print(s1 + s2)